# MongoDB configurations
spring:
  config:
    import: optional:application-secret.yml
  data:
    mongodb:
      database: viet-chat
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
      uri: mongodb://root:root@ec2-46-137-198-199.ap-southeast-1.compute.amazonaws.com:27017/

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
server:
  servlet:
    context-path: /api


# Swagger configurations
springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path:
    enabled: false

app:
  auth:
    tokenSecret: lNLp8m5m86mRQLgNU7UnhGqfBbNdNYAM45YOFwZmP1w=
    refreshTokenExpirationMilliseconds: 1209600000
    accessTokenExpirationMilliseconds: 1800000
    resetTokenExpirationMilliseconds: 300000

management:
  endpoint:
    health:
      enabled: false
  health:
    defaults:
      enabled: false
